// <auto-generated />
using HotelReposPattern.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelReposPattern.Migrations
{
    [DbContext(typeof(HotelContext))]
    [Migration("20240902094940_create")]
    partial class create
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelReposPattern.Models.Hotel", b =>
                {
                    b.Property<int>("HotelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HotelId"));

                    b.Property<string>("HotelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HotelId");

                    b.ToTable("HotelSet");

                    b.HasData(
                        new
                        {
                            HotelId = 1,
                            HotelName = "Taj Hotel"
                        },
                        new
                        {
                            HotelId = 2,
                            HotelName = "Phenoix"
                        });
                });

            modelBuilder.Entity("HotelReposPattern.Models.Room", b =>
                {
                    b.Property<int>("RoomNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomNo"));

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomNo");

                    b.HasIndex("HotelId");

                    b.ToTable("RoomSet");

                    b.HasData(
                        new
                        {
                            RoomNo = 1,
                            HotelId = 0,
                            Price = 35000m,
                            RoomType = "AC"
                        },
                        new
                        {
                            RoomNo = 2,
                            HotelId = 0,
                            Price = 4000m,
                            RoomType = " Normal"
                        });
                });

            modelBuilder.Entity("HotelReposPattern.Models.Room", b =>
                {
                    b.HasOne("HotelReposPattern.Models.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("HotelReposPattern.Models.Hotel", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
