// src/app/models/order-item.model.ts

export interface OrderItem {
productName: any;
    orderItemId?: number; // Optional because it will be generated by the backend
    orderId: number;
    productId: number;
    quantity: number;
    price: number;
  }
  