// <auto-generated />
using System;
using Entity_framework.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entity_framework.Migrations
{
    [DbContext(typeof(CustomerDbconnect))]
    [Migration("20240830073741_customercreate")]
    partial class customercreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entity_framework.Models.Customer", b =>
                {
                    b.Property<int>("custID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("custID"));

                    b.Property<string>("custName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("custage")
                        .HasColumnType("int");

                    b.Property<string>("custcity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("custID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Entity_framework.Models.Order", b =>
                {
                    b.Property<int>("orderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("orderId"));

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("custID")
                        .HasColumnType("int");

                    b.HasKey("orderId");

                    b.HasIndex("custID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Entity_framework.Models.Order", b =>
                {
                    b.HasOne("Entity_framework.Models.Customer", "Customer")
                        .WithMany("orders")
                        .HasForeignKey("custID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Entity_framework.Models.Customer", b =>
                {
                    b.Navigation("orders");
                });
#pragma warning restore 612, 618
        }
    }
}
