import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { UserService } from '../../user.service';
import { User } from '../../../Models/User';

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './register.component.html',
  styleUrl: './register.component.css'
})
export class RegisterComponent {
  name = '';
  email = '';
  password = '';
  role = 'Customer';

  constructor(private userService: UserService, private router: Router) {}

  register() {
    const newUser: User = {
      userId: 0, // This will be generated by the backend
      name: this.name,
      email: this.email,
      password: this.password,
      role: this.role
    };

    this.userService.registerUser(newUser).subscribe(
      response => {
        console.log('User registered successfully', response);
        // You can navigate to another page or show a success message here
      },
      error => {
        console.error('Error registering user', error);
      }
    );
    alert("Registered Sucessfully");
    this.router.navigate(['/login']);
  }

  navigateToLogin(): void {
    this.router.navigate(['/login']);
  }
}
