import { Component } from '@angular/core';
import { Company } from '../company';
import { APIService } from '../api.service';
import { Router } from '@angular/router';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ReactiveFormsModule } from '@angular/forms';


@Component({
  selector: 'app-add-company',
  standalone: true,
  imports: [CommonModule,FormsModule,ReactiveFormsModule],
  templateUrl: './add-company.component.html',
  styleUrl: './add-company.component.css'
})
export class AddCompanyComponent {
  //company:Company={id:0,name:''};
  // constructor(private apiser:APIService,private router:Router){
    
  // }
  // onSubmit(): void {
  //   this.apiser.post(this.company, { responseType: 'text' }).subscribe({
  //     next: (response) => {
  //       console.log('Company added successfully', response);
  //       this.router.navigate(['/']);
  //     },
  //     error: (error) => {
  //       console.error('Error adding company', error);
  //     },
  //     complete: () => {
  //       console.log('Request complete');
  //     }
  //   });
 // }
  
 companyForm: FormGroup;

 constructor(private apiService: APIService, private fb: FormBuilder) {
   this.companyForm = this.fb.group({
     name: ['', Validators.required]
   });
 }

 addCompany() {
   if (this.companyForm.valid) {
     const newCompany: Company = {
       id: 0, // id is auto-generated by the backend
       name: this.companyForm.value.name
     };

     this.apiService.post(newCompany, { responseType: 'json' }).subscribe(
       response => {
         console.log('Company added successfully', response);
         this.companyForm.reset();
       },
       error => {
         console.error('Error adding company', error);
       }
     );
   } else {
     console.log('Form is invalid');
   }
 }
}
